server:
  port: 7777
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  cloud:
    bootstrap:
      enable: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: aurora-gateway
