server:
  port: 7777
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: aurora-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: aurora-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
