server:
  port: 7777
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: aurora-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: aurora-gateway
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: aurora-admin1
          uri: lb://aurora-admin
          predicates:
            - Path=/admin/**


management:
  endpoints:
    web:
      exposure:
        include: "*"
