server:
  port: 7777
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      # 设置跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: true
    bootstrap:
      enable: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: aurora-gateway

springdoc:
  swagger-ui:
    use-root-path: true
#    urls:
#      - name: aurora-article
#        url: /v3/api-docs/aurora-article
#      - name: aurora-file
#        url: /v3/api-docs/aurora-file