server:
  port: 7777
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: aurora-gateway
  cloud:
    sentinel:
      filter:
        enabled: false
      scg:
        fallback:
          mode: response
          response-status: 200
          response-body: '{"code":404,"data":{},"message":"请求太快了,请稍后在试┭┮﹏┭┮","success":false}'
      transport:
        port: 8719
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: aurora-gateway
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: aurora-admin1
          uri: lb://aurora-admin
          predicates:
            - Path=/admin/**
        - id: aurora-comment
          uri: lb://aurora-comment
          predicates:
            - Path=/comment/**
        - id: aurora-article
          uri: lb://aurora-article
          predicates:
            - Path=/blog/**
        - id: aurora-message
          uri: lb://aurora-message
          predicates:
            - Path=/message/**
        - id: aurora-auth-server
          uri: lb://aurora-auth-server
          predicates:
            - Path=/auth/**
        - id: aurora-auth-login
          uri: lb://aurora-auth-server
          predicates:
            - Path=/login/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
aurora:
  oauth:
    secret-key: auroraaadkfhasdfuywasdfkjahdsfuewkrnbsdjtywq8745ghsdfsgdfhsdfgerbjhsdtfquewrw9erygtwertfysatf
