server:
  port: 8888
  compression:
    enabled: false
spring:
  main:
    allow-circular-references: true
  redis:
    database: 1
    host: localhost
    password: ''
    port: 6379
    jedis:
      pool:
        max-active: 15
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aurora_auth_server?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Cqy19981202
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: aurora-auth-server
mybatis:
  mapper-locations: classpath:mapper/**
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 自定义的配置

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    xyz.xcye.web.common.service.feign.MessageLogFeignService: DEBUG

feign:
  circuitbreaker:
    enabled: true
    group:
      enabled: true
aurora:
  oauth:
    access-token-validity-seconds: 259200
    refresh-token-validity-seconds: 259200
    redis-delete-retry: 4
    max-login-failure: 4
    re-login-minute: 5
    tx-map-api: https://apis.map.qq.com/ws/location/v1/ip?key=PU6BZ-VVO6V-66QP2-UNRJQ-K2JCO-24BCX
    secret-key: auroraaadkfhasdfuywasdfkjahdsfuewkrnbsdjtywq8745ghsdfsgdfhsdfgerbjhsdtfquewrw9erygtwertfysatf
  snow-flake-datacenter-id: 1
  snow-flake-worker-id: 2