services:
  nacos_standalone:
    env_file:
      - ./.env
    image: nacos/nacos-server:${NACOS_VERSION}
    hostname: nacos_standalone_host
    container_name: nacos_standalone
    restart: always
    ports:
      - "0.0.0.0:8848:8848"
      - "0.0.0.0:9849:9849"
      - "0.0.0.0:9848:9848"
      - "0.0.0.0:7848:7848"
    networks:
      - nacos_network
      - micro_network
    volumes:
      - type: volume
        source: nacos_standalone_data
        target: /home/nacos
      - /opt/docker/project/nacos/logs:/home/nacos/logs
      - ./conf:/home/nacos/conf:ro
      - /opt/docker/project/nacos/init.d:/home/nacos/init.d
volumes:
  nacos_standalone_data:
    name: nacos_standalone_data
    driver: local
networks:
  nacos_network:
    name: nacos_network
    driver: bridge
  micro_network:
    external: false
    name: micro_network
    driver: bridge

