server:
  port: 6767
spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

# swagger-ui custom path

aurora:
  swagger:
    author:
      name: aurora
      url: https://aurora.xcye.xyz
      email: 2291308094@qq.com
    api-info:
      title: 博客文件API
      description: 这是Aurora主题的博客文件api
      version: 1.0.0
      license: MIT
      license-url: https://github.com/vuepress-aurora/vuepress-theme-aurora/blob/master/LICENSE