services:
  mysql:
    hostname: mysql_host
    env_file:
      - ./.env.mysql
    container_name: mysql8_db
    image: mysql:8.1.0
    expose:
      - "${PROJECT_MYSQL_PORT:-3306}:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      - type: bind
        source: ./config/mysql/conf.d
        target: /etc/mysql/conf.d
        read_only: true
      - type: bind
        source: ../../docs/mysql/v2/table-data
        target: /docker-entrypoint-initdb.d
    ports:
      - "0.0.0.0:${PROJECT_MYSQL_PORT:-3306}:3306"
    restart: ${RESTART_OPTION:-no}
    networks:
      - mysql_network
      - micro_network
  nacos_standalone:
    env_file:
      - ./.env.nacos
    image: nacos/nacos-server:${NACOS_VERSION}
    hostname: nacos_standalone_host
    container_name: nacos_standalone
    restart: ${RESTART_OPTION:-no}
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:8848:8848"
      - "0.0.0.0:9849:9849"
      - "0.0.0.0:9848:9848"
      - "0.0.0.0:7848:7848"
    networks:
      - nacos_network
      - micro_network
    volumes:
      - type: volume
        source: nacos_standalone_data
        target: /home/nacos
      - ${WORK_DIR}/nacos/logs:/home/nacos/logs
      - ./config/nacos:/home/nacos/conf:ro
      - ${WORK_DIR}/nacos/init.d:/home/nacos/init.d
  rabbitmq:
    container_name: rabbitMq_host
    hostname: docker_rabbitmq
    image: rabbitmq:3.12.4-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: Cqy19981202
    volumes:
      - ${WORK_DIR}/rabbitmq/log:/var/log/rabbitmq:rw
      #- /opt/docker/project/rabbitmq/conf:/etc/rabbitmq:rw
      - type: volume
        source: rabbitmq_data
        target: /var/lib/rabbitmq
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    restart: ${RESTART_OPTION:-no}
    networks:
      - rabbitmq_network
      - micro_network
  redis:
    hostname: redis_host
    container_name: redis_db
    image: redis:7.2.1
    expose:
      - "35680:35680"
    volumes:
      - type: volume
        source: redis_data
        target: /data
      - ./config/redis:/usr/local/etc/redis:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "0.0.0.0:35680:35680"
    restart: ${RESTART_OPTION:-no}
    networks:
      - redis_network
      - micro_network
volumes:
  mysql_data:
    name: mysql_data_volume
    driver: local
  nacos_standalone_data:
    name: nacos_standalone_data
    driver: local
  rabbitmq_data:
    name: rabbitmq_data_volume
    driver: local
  redis_data:
    name: redis_data_volume
    driver: local
networks:
  # mysql自己的网络
  mysql_network:
    name: mysql_network
    driver: bridge
    external: false
  nacos_network:
    name: nacos_network
    driver: bridge
    external: false
  rabbitmq_network:
    driver: bridge
    name: rabbitmq_network
    external: false
  redis_network:
    name: redis_network
    driver: bridge
    external: false
  # 微服务环境网络
  micro_network:
    name: micro_network
    driver: bridge
    external: false
