server:
  port: 7070

spring:
  # 一定要开启下面这个，否则nacos中的配置不会被获取到
  bootstrap:
    enable: true
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aurora:
  swagger:
    author:
      name: aurora
      url: https://aurora.xcye.xyz
      email: 2291308094@qq.com
    api-info:
      title: 博客消息API
      description: 这是Aurora主题的博客消息api
      version: 1.0.0
      license: MIT
      license-url: https://github.com/vuepress-aurora/vuepress-theme-aurora/blob/master/LICENSE