server:
  port: 7070

spring:
  # 一定要开启下面这个，否则nacos中的配置不会被获取到
  bootstrap:
    enable: true
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

