server:
  compression:
    enabled: false
  port: 8890
spring:
  profiles:
    active: dev
  cloud:
    bootstrap:
      enable: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath*:/mapper/*.xml