services:
  aurora_admin:
    image: ${DOCKER_REGISTRY:-hub.xcye.xyz}/${DOCKER_NAMESPACE:-aurora-blog}/admin-boot:latest
    container_name: aurora_admin
    hostname: aurora_admin_host
    restart: ${COMPOSE_SERVICE_RESTART:-no}
    volumes:
      - type: bind
        source: ${PROJECT_LOG_STORAGE_PATH:-/tmp/aurora-log}
        target: /tmp/aurora-log
    networks:
      - micro_network
      - admin_network
    ports:
      - ${AURORA_ADMIN_SERVER_ADDR:-127.0.0.1:30100}:8088
      - ${AURORA_ADMIN_SERVER_DEBUG_ADDR:-0.0.0.0:30150}:50001
  aurora_article:
    image: ${DOCKER_REGISTRY:-hub.xcye.xyz}/${DOCKER_NAMESPACE:-aurora-blog}/article-boot:latest
    container_name: aurora_article
    hostname: aurora_article
    restart: ${COMPOSE_SERVICE_RESTART:-no}
    volumes:
      - type: bind
        source: ${PROJECT_LOG_STORAGE_PATH:-/tmp/aurora-log}
        target: /tmp/aurora-log
    networks:
      - micro_network
      - admin_network
    ports:
      - ${AURORA_ARTICLE_SERVER_ADDR:-127.0.0.1:30200}:8088
      - ${AURORA_ARTICLE_SERVER_DEBUG_ADDR:-0.0.0.0:30250}:50001
  aurora_auth:
    image: ${DOCKER_REGISTRY:-hub.xcye.xyz}/${DOCKER_NAMESPACE:-aurora-blog}/auth-server-boot:latest
    container_name: aurora_auth
    hostname: aurora_auth
    restart: ${COMPOSE_SERVICE_RESTART:-no}
    volumes:
      - type: bind
        source: ${PROJECT_LOG_STORAGE_PATH:-/tmp/aurora-log}
        target: /tmp/aurora-log
    networks:
      - auth_server_network
      - micro_network
    ports:
      - ${AURORA_AUTH_SERVER_ADDR:-127.0.0.1:30300}:8088
      - ${AURORA_AUTH_SERVER_DEBUG_ADDR:-0.0.0.0:30350}:50001
  aurora_comment:
    image: ${DOCKER_REGISTRY:-hub.xcye.xyz}/${DOCKER_NAMESPACE:-aurora-blog}/comment-boot:latest
    container_name: aurora_comment
    hostname: aurora_comment
    restart: ${COMPOSE_SERVICE_RESTART:-no}
    volumes:
      - type: bind
        source: ${PROJECT_LOG_STORAGE_PATH:-/tmp/aurora-log}
        target: /tmp/aurora-log
    networks:
      - comment_network
      - micro_network
    ports:
      - ${AURORA_COMMENT_SERVER_ADDR:-127.0.0.1:30400}:8088
      - ${AURORA_COMMENT_SERVER_DEBUG_ADDR:-0.0.0.0:30450}:50001
  aurora_file:
    image: ${DOCKER_REGISTRY:-hub.xcye.xyz}/${DOCKER_NAMESPACE:-aurora-blog}/file-boot:latest
    container_name: aurora_file
    hostname: aurora_file
    restart: ${COMPOSE_SERVICE_RESTART:-no}
    volumes:
      - type: bind
        source: ${PROJECT_LOG_STORAGE_PATH:-/tmp/aurora-log}
        target: /tmp/aurora-log
    networks:
      - file_network
      - micro_network
    ports:
      - ${AURORA_FILE_SERVER_ADDR:-127.0.0.1:30500}:8088
      - ${AURORA_FILE_SERVER_DEBUG_ADDR:-0.0.0.0:30550}:50001
  aurora_gateway:
    image: ${DOCKER_REGISTRY:-hub.xcye.xyz}/${DOCKER_NAMESPACE:-aurora-blog}/gateway-boot:latest
    container_name: aurora_gateway
    hostname: aurora_gateway
    restart: ${COMPOSE_SERVICE_RESTART:-no}
    volumes:
      - type: bind
        source: ${PROJECT_LOG_STORAGE_PATH:-/tmp/aurora-log}
        target: /tmp/aurora-log
    networks:
      - gateway_network
      - micro_network
    ports:
      - ${AURORA_GATEWAY_SERVER_ADDR:-127.0.0.1:30600}:8088
      - ${AURORA_GATEWAY_SERVER_DEBUG_ADDR:-0.0.0.0:30650}:50001
  aurora_message:
    image: ${DOCKER_REGISTRY:-hub.xcye.xyz}/${DOCKER_NAMESPACE:-aurora-blog}/message-boot:latest
    container_name: aurora_message
    hostname: aurora_message
    restart: ${COMPOSE_SERVICE_RESTART:-no}
    volumes:
      - type: bind
        source: ${PROJECT_LOG_STORAGE_PATH:-/tmp/aurora-log}
        target: /tmp/aurora-log
    networks:
      - message_network
      - micro_network
    ports:
      - ${AURORA_MESSAGE_SERVER_ADDR:-127.0.0.1:30700}:8088
      - ${AURORA_MESSAGE_SERVER_DEBUG_ADDR:-0.0.0.0:30750}:50001

# 定义网络
networks:
  # 定义微服务网络，所有服务都加入到该网络中
  micro_network:
    external: true
    name: micro_network
    driver: bridge
  # 定义各服务网络
  admin_network:
    external: false
    name: admin_network
    driver: bridge
  article_network:
    external: false
    name: article_network
    driver: bridge
  file_network:
    external: false
    name: file_network
    driver: bridge
  comment_network:
    external: false
    name: comment_network
    driver: bridge
  auth_server_network:
    external: false
    name: auth_server_network
    driver: bridge
  gateway_network:
    external: false
    name: gateway_network
    driver: bridge
  message_network:
    external: false
    name: message_network
    driver: bridge