server:
  port: 8088
  compression:
    enabled: false
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

#aurora:
#  amqp:
#    exchanges:
#      # 发送邮件的交换机
#      - exchange: aurora.send.email.common.exchange
#        exchange-type: topic
#        dead-letter-exchange: aurora.send.email.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          # 发送html邮件
#          - queue: send.html.mail.queue
#            dead-letter-queue: send.html.mail.dead.letter.queue
#            routing-key: send.html.amil.routing
#            dead-letter-routing-key: send.html.mail.dead.letter.routing
#
#          - queue: send.simple.text.mail.queue
#            dead-letter-queue: send.simple.text.mail.dead.letter.queue
#            routing-key: send.simple.text.mail.routing
#            dead-letter-routing-key: send.simple.text.mail.dead.letter.routing
#            # 发送错误消息的交换机
#      - exchange: aurora.send.mistake.exchange
#        exchange-type: topic
#        dead-letter-exchange: aurora.send.mistake.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          - queue: aurora.mistake.queue
#            dead-letter-queue: aurora.mistake.dead.letter.queue
#            routing-key: aurora.mistake.routing.key
#            dead-letter-routing-key: aurora.mistake.dead.letter.routing.key
#              # 发送操作用户数据的交换机
#      - exchange: aurora.send.operate.user.exchange
#        exchange-type: topic
#        dead-letter-exchange: aurora.send.operate.user.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          - queue: aurora.operate.user.binding.email.queue
#            dead-letter-queue: aurora.operate.user.binding.email.dead.letter.queue
#            routing-key: aurora.operate.user.binding.email.routing
#            dead-letter-routing-key: aurora.operate.user.binding.email.dead.letter.routing
#
#          - queue: aurora.operate.user.lock.account.queue
#            dead-letter-queue: aurora.operate.user.lock.account.dead.letter.queue
#            routing-key: aurora.operate.user.lock.account.routing.key
#            dead-letter-routing-key: aurora.operate.user.lock.account.dead.letter.routing.key
#
#          - queue: aurora.update.role.permission.queue
#            dead-letter-queue: aurora.update.role.permission.dead.letter.queue
#            routing-key: aurora.update.role.permission.routing.key
#            dead-letter-routing-key: aurora.update.role.permission.dead.letter.routing
#
#          - queue: aurora.update.white.url.queue
#            dead-letter-queue: aurora.update.white.url.dead.letter.queue
#            routing-key: aurora.update.white.url.routing.key
#            dead-letter-routing-key: aurora.update.white.url.dead.letter.routing
#              # 发送评论的交换机
#      - exchange: aurora.send.comment.exchange
#        exchange-type: topic
#        dead-letter-exchange: aurora.send.comment.dead.letter.exchange
#        dead-letter-exchange-type: direct
#        queues:
#          - queue: aurora.PAGE.comment.queue
#            dead-letter-queue: aurora.PAGE.comment.dead.letter.queue
#            routing-key: aurora.PAGE.routingKey
#            dead-letter-routing-key: aurora.PAGE.comment.dead.letter.routingKey
#    default-max-length: 25
#    default-ttl: 6000




