server:
  port: 8888

#  spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aurora_blog?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Cqy19981202
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: aurora-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"