server:
  port: 8888

#  spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: aurora-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"